/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_uInputJNI */
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <linux/input.h>
#include <linux/uinput.h>
#include <stdio.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>

/* Button actions */
#define ACTION_DOWN 1
#define ACTION_UP   0


#ifndef _Included_utils_uInputJNI
#define _Included_utils_uInputJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_uInputJNI
 * Method:    setup_uinput_device
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_utils_uInputJNI_setup_1uinput_1device
  (JNIEnv *, jobject);

/*
 * Class:     utils_uInputJNI
 * Method:    trigger_single_key_click
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_utils_uInputJNI_trigger_1single_1key_1click
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_uInputJNI
 * Method:    trigger_axis_X_event
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_utils_uInputJNI_trigger_1axis_1X_1event
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_uInputJNI
 * Method:    trigger_axis_Y_event
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_utils_uInputJNI_trigger_1axis_1Y_1event
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_uInputJNI
 * Method:    close_device
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_utils_uInputJNI_close_1device
  (JNIEnv *, jobject);


  	int uinp_fd;
	struct uinput_user_dev uinp;       // uInput device structure
	struct input_event event; // Input device structure

	int setup_uinput_device();
	void send_click_events();
	int send_keyevent(int key_code, int is_down);
	void send_key_click(int key_code);


	int make_gamepad_MIT();

#ifdef __cplusplus
}
#endif
#endif
